In [1]:
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../../spreadsheets/prestige.csv')
df

                     job  education  income  women  prestige  census  type
0     gov.administrators      13.11   12351  11.16      68.8    1113  prof
1       general.managers      12.26   25879   4.02      69.1    1130  prof
2            accountants      12.77    9271  15.70      63.4    1171  prof
3    purchasing.officers      11.42    8865   9.11      56.8    1175  prof
4               chemists      14.62    8403  11.68      73.5    2111  prof
..                   ...        ...     ...    ...       ...     ...   ...
97           bus.drivers       7.58    5562   9.47      35.9    9171    bc
98          taxi.drivers       7.93    4224   3.59      25.1    9173    bc
99          longshoremen       8.37    4753   0.00      26.1    9313    bc
100          typesetters      10.00    6462  13.58      42.2    9511    bc
101          bookbinders       8.55    3617  70.87      35.2    9517    bc

[102 rows x 7 columns]

In [ ]:
# Check the sample size and average income for each group
df.groupby('type').count()

      job  education  income  women  prestige  census
type
bc     44         44      44     44        44      44
prof   31         31      31     31        31      31
wc     23         23      23     23        23      23

In [15]:
df.groupby('type')['income'].mean()

type
bc       5374.136364
prof    10559.451613
wc       5052.304348
Name: income, dtype: float64

In [19]:
df_sub = df[df['type'].isin(['wc', 'bc'])]
df_sub

                     job  education  income  women  prestige  census type
27         nursing.aides       9.45    3485  76.14      34.9    3135   bc
30   medical.technicians      12.79    5180  76.04      67.5    3156   wc
32   radio.tv.announcers      12.71    7562  11.15      57.6    3337   wc
34           secretaries      11.59    4036  97.51      46.0    4111   wc
35               typists      11.49    3148  95.97      41.9    4113   wc
..                   ...        ...     ...    ...       ...     ...  ...
97           bus.drivers       7.58    5562   9.47      35.9    9171   bc
98          taxi.drivers       7.93    4224   3.59      25.1    9173   bc
99          longshoremen       8.37    4753   0.00      26.1    9313   bc
100          typesetters      10.00    6462  13.58      42.2    9511   bc
101          bookbinders       8.55    3617  70.87      35.2    9517   bc

[67 rows x 7 columns]

In [25]:
income_bc = df_sub[df_sub['type'] == 'bc']['income']
income_wc = df_sub[df_sub['type'] == 'wc']['income']
income_bc.mean()

np.float64(5374.136363636364)

In [24]:
income_wc.mean()

np.float64(5052.304347826087)

In [27]:

shapiro_bc = stats.shapiro(income_bc)
shapiro_wc = stats.shapiro(income_wc)
shapiro_bc

ShapiroResult(statistic=np.float64(0.9662506459293128), pvalue=np.float64(0.22181723139990506))

In [28]:
shapiro_wc

ShapiroResult(statistic=np.float64(0.9260685765517781), pvalue=np.float64(0.08995567654171996))