In [18]:
import pandas as pd
from scipy import stats
from scipy.stats import chi2_contingency
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
# Cross Tabulation
table = pd.crosstab(df['pclass'], df['alive'])
table

alive    no  yes
pclass
1        80  136
2        97   87
3       372  119

In [14]:
# calculating survival rate by cabin
cabin1_rate = table['yes'][1] / (table['yes'][1] + table['no'][1])
cabin1_rate

np.float64(0.6296296296296297)

In [15]:
cabin2_rate = table['yes'][2] / (table['yes'][2] + table['no'][2])
cabin2_rate

np.float64(0.47282608695652173)

In [16]:
cabin3_rate = table['yes'][3] / (table['yes'][3] + table['no'][3])
cabin3_rate

np.float64(0.24236252545824846)

In [19]:
chi2_stat, p_val, dof, expected_freq = chi2_contingency(table)
pd.DataFrame(expected_freq, index=table.index, columns=table.columns)

alive           no         yes
pclass
1       133.090909   82.909091
2       113.373737   70.626263
3       302.535354  188.464646

In [20]:
print("\n--- Chi-Square Test Results ---")
print(f"Chi-square Statistic: {chi2_stat:.4f}")
print(f"p-value: {p_val}")
print(f"Degrees of Freedom: {dof}")

--- Chi-Square Test Results ---
Chi-square Statistic: 102.8890
p-value: 4.549251711298793e-23
Degrees of Freedom: 2