In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('../../spreadsheets/iris.csv')

In [7]:
df_agg = df.groupby('species').mean()
df_agg

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [9]:
df_agg = df.groupby('species').std()
df_agg

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          0.352490     0.381024      0.173511     0.107210
versicolor      0.516171     0.313798      0.469911     0.197753
virginica       0.635880     0.322497      0.551895     0.274650

In [11]:
df_cars = pd.read_csv('../../spreadsheets/mtcars.csv')

df_cars_agg = df_cars.groupby(['cyl', 'vs']).max()
df_cars_agg

                   model   mpg   disp   hp  drat     wt   qsec  am  gear  carb
cyl vs
4   0      Porsche 914-2  26.0  120.3   91  4.43  2.140  16.70   1     5     2
    1         Volvo 142E  33.9  146.7  113  4.93  3.190  22.90   1     5     2
6   0      Mazda RX4 Wag  21.0  160.0  175  3.90  2.875  17.02   1     5     6
    1            Valiant  21.4  258.0  123  3.92  3.460  20.22   0     4     4
8   0   Pontiac Firebird  19.2  472.0  335  4.22  5.424  18.00   1     5     8